name: malabis_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  #Font Import
  font_awesome_flutter: ^10.8.0

  #State Provider
  get:
  carousel_slider: ^5.0.0
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/MalabisLogo.png"
  adaptive_icon_foreground: "assets/images/MalabisLogo.png"

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
