// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPaEixO04yMF7bUHhSd4lG2KOy8c6_Sic',
    appId: '1:330936671582:web:94d8d89e4a76e0559f03cf',
    messagingSenderId: '330936671582',
    projectId: 'malabisproject',
    authDomain: 'malabisproject.firebaseapp.com',
    storageBucket: 'malabisproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxvtw0N43da9LKSv5h5a31x-bZceEzfVw',
    appId: '1:330936671582:android:35611e26ec5273db9f03cf',
    messagingSenderId: '330936671582',
    projectId: 'malabisproject',
    storageBucket: 'malabisproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtB-Znfc3nK9q17a62z3LEZlSPP7W55_c',
    appId: '1:330936671582:ios:7c58bd24c300b2a79f03cf',
    messagingSenderId: '330936671582',
    projectId: 'malabisproject',
    storageBucket: 'malabisproject.firebasestorage.app',
    androidClientId: '330936671582-qlicin7c7b7khkplldt0s43cme83are7.apps.googleusercontent.com',
    iosClientId: '330936671582-pcn0gk1d3g3tt0s31nirhsv0pabo6od5.apps.googleusercontent.com',
    iosBundleId: 'com.example.malabisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtB-Znfc3nK9q17a62z3LEZlSPP7W55_c',
    appId: '1:330936671582:ios:7c58bd24c300b2a79f03cf',
    messagingSenderId: '330936671582',
    projectId: 'malabisproject',
    storageBucket: 'malabisproject.firebasestorage.app',
    androidClientId: '330936671582-qlicin7c7b7khkplldt0s43cme83are7.apps.googleusercontent.com',
    iosClientId: '330936671582-pcn0gk1d3g3tt0s31nirhsv0pabo6od5.apps.googleusercontent.com',
    iosBundleId: 'com.example.malabisApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPaEixO04yMF7bUHhSd4lG2KOy8c6_Sic',
    appId: '1:330936671582:web:7c3dd6a81d81583b9f03cf',
    messagingSenderId: '330936671582',
    projectId: 'malabisproject',
    authDomain: 'malabisproject.firebaseapp.com',
    storageBucket: 'malabisproject.firebasestorage.app',
  );
}
